[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
LatentSDEBayes = "21909e9c-fb2a-466a-bd10-00a70ebfe64a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
