name = "LatentSDEBayes"
uuid = "21909e9c-fb2a-466a-bd10-00a70ebfe64a"
authors = ["Ron-27 <ronmaor@sas.upenn.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StableHashTraits = "c5dd0088-6c3f-4803-b00e-f31a60c170fa"

[compat]
ComponentArrays = "0.15.32"
Distributions = "0.25.123"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
SpecialFunctions = "2.7.1"
StableHashTraits = "2.0.2"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
